### PR TITLE
Unencapsulate Range utility functions

### PR DESCRIPTION
**Pull request by Hc747**
Unencapsulate Range bounds checking utility functions.

`Range#hasEqualBounds`
`Range#isBoundedOpen`
`Range#isBounded`

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks, I'll review it when I have some time.

**Review by piotrooo — CHANGES_REQUESTED** [review]
Other implementations for Range should be changed as well.

**Comment by Hc747** [comment]
> Other implementations for Range should be changed as well.

Resolved. Didn't realise this implementation was duplicated across modules. Good catch!

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
